package com.systa.ai.service;

import com.systa.ai.domain.TicketRequest;
import com.systa.ai.entity.HelpDeskTicket;
import com.systa.ai.repository.HelpDeskTicketRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;

@Service
public class HelpDeskTicketService {

    private final HelpDeskTicketRepository helpDeskTicketRepository;

    public HelpDeskTicketService(final HelpDeskTicketRepository helpDeskTicketRepository) {
        this.helpDeskTicketRepository = helpDeskTicketRepository;
    }

    public HelpDeskTicket createHelpDeskTicket(final TicketRequest ticketRequest,
                                     final String userName) {
        // Logic to create a help desk ticket and save it to the database

        final HelpDeskTicket ticket = new HelpDeskTicket(
                null, // ID will be generated by the database
                userName,
                ticketRequest.issueDescription(),
                "OPEN", // Initial status
                LocalDate.now(), // Created date
                LocalDate.now().plusDays(7) // Resolved date will be null until the ticket is resolved
        );

        return helpDeskTicketRepository.save(ticket);
    }

    public List<HelpDeskTicket> getTicketsByUserName(final String userName) {
        // Logic to retrieve help desk tickets for a specific user
        return helpDeskTicketRepository.findByUsername(userName);
    }
}
